### ISSUE TITLE
Correct collaborators names in readme.md

### ISSUE THREAD

**Issue by sangar-happy** [LearnToCodeApp-Group/LearnToCodeApp#10]
**Brief summary of the bug**
The collaborator names are in the same line.

Steps to reproduce the behaviour:
1. Go to [readme.md](https://github.com/LearnToCodeApp-Group/LearnToCodeApp/blob/master/readme.md)
2. Scroll down to **Collaborators**
3. See the collaborators name

**Expected behaviour**
The names should occupy single line.

**Screenshots**
https://imgur.com/a/owiHIkb

**Additional context**
To see the names in the next line, there must be a blank line in between the markdown. Also check the **Preview** tab hile editing markdown files in GitHub.

**Comment by sagarc03** [comment]
When you it says correct the collaborators name, you want people to add or just correct these two?

**Comment by sangar-happy** [comment]
Both. Add your name as a collab. and correct the previous ones.

**Comment by WarmlindAlbin** [comment]
Yeah i've done it and opened a PR

**Comment by sagarc03** [comment]
I am going to mark this as a close issue. We can open a new issue to just ask all collaborators to add their name as a first issue.

**Comment by sangar-happy** [comment]
Please open a new issue regarding this.
