### ISSUE TITLE
Correct-Conduct-Titles

### ISSUE THREAD

**Issue by DjangoWill2018** [LearnToCodeApp-Group/LearnToCodeApp#5]
**Brief summary of the bug**
The sub-headings in the Code of Conduct do not have the correct markdown.

**What happened immediately before the bug occurs?**
N/A

**Expected behaviour**
The sub-headings should be formatted as second/third level html headings.

**Current behaviour**
The sub-headings are shown starting with hash signs.

**Screenshots**
If possible, please add screenshots to help explain your problem.

**Context**
Linux Mint / Windows 10

Smartphone (please complete the following information):
N/A

**Additional context**
The original file is a "md" or markdown file. This is similar to the "markup" used in html but uses different tags. You will need to:

1. Check the ReadTheDocs page explaining how to contribute code.
2. Lookup the correct syntax for the sub-headings and commit the changes to your branch.
3. Make a Pull Request. A Pull Request means you are asking for your changes to be incorporated into the development branch.
![issue1](https://user-images.githubusercontent.com/46193827/50605453-3bb60000-0eba-11e9-9f76-03b4651098b1.PNG)

**Comment by RushikSubba** [comment]
Changed it and submitted a pul request.
